version: "3.3"
services:
  zeppelin:
    image: apache/zeppelin:0.9.0
    environment: 
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
    ports:
      - 8080:8080
     # - 4040-4050:4040-4050
    volumes:
      - ./notebook:/notebook
      - ./logs:/logs
